# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  # Verifies the workflow is skipped because the test would fail since it
  # doesn't exist
  - app_dir: kubeflow/kubeflow/testing/lmnop
    component: click_deploy_test
    name: skipmeplease
    job_types:
    - presubmit
    include_dirs:
    - xyz/*
    params:
      workflowName: skipmeplease

  # Run unittests
  - py_func: kubeflow.testing.ci.kf_unittests.create_workflow
    name: py-unittests
    kwargs: {}

  # TODO(jlewi): The tests are commented out below because we wanted to have some examples
  # of what the syntax looks like but these tests are not really suitable for kubeflow/testing
  # and they were failing blocking kubeflow/testing#622 from being merged.
  # we should fix this in a follow on PR. The best thing to do would probably
  # be to add a Tekton pipeline to run lint or unittests.
  # Demo purpose change to run Tekton pipelines on Prow.
  #- tekton_run: kubeflow/testing/tekton/testing/nb-test-run.yaml
  #  tekton_teardown: kubeflow/testing/tekton/testing/dummy-teardown-run.yaml
  #  tekton_teardown_params:
  #  - name: utter
  #    value: foo
  #  name: tekton-master
  #  include_dirs:
  #  - py/*

  #- tekton_run: kubeflow/testing/tekton/testing/nb-test-run.yaml
  #  tekton_params:
  #  - name: testing-cluster-pattern
  #    value: 'kf-v1-(?!n\d\d)'
  #  tekton_teardown: kubeflow/testing/tekton/testing/dummy-teardown-run.yaml
  #  tekton_teardown_params:
  #  - name: utter
  #    value: bar
  #  name: tekton-v1
  #  include_dirs:
  #  - py/*
