apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: auto-deploy
  clusterName: kubeflow-testing
  namespace: kubeflow-test-infra
spec:
  # Daily at 10p
  schedule: "0 22 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: deploy-worker
            image: gcr.io/kubeflow-ci/deploy-worker:live
            command:
            - /usr/local/bin/init.sh
            - /src # SRC_DIR
            - kubeflow # REPO_OWNER
            - kubeflow-ci # PROJECT
            - kubeflow-testing # WORKER_CLUSTER
            volumeMounts:
            - name: gcp-credentials
              mountPath: "/secret/gcp-credentials"
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: gcp-credentials
            secret:
              secretName: gcp-credentials
