apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: auto-deploy
  clusterName: kubeflow-testing
  namespace: kubeflow-test-infra
spec:
  concurrencyPolicy: "Forbid"
  # Daily at 10p
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
#          initContainers:
#          - name: snapshot-worker
#            image: gcr.io/kubeflow-ci/snapshot-worker:latest
#            env:
#            - name: GOOGLE_APPLICATION_CREDENTIALS
#              value: /secret/gcp-credentials/key.json
#            command:
#            - python
#            - /usr/local/bin/snapshot_kf_deployment.py
#            - kubeflow
#            - testing
#            - --project=kubeflow-ci
#            - --repo_owner=kubeflow
#            volumeMounts:
#            - name: github-token
#              mountPath: "/secret/github-token"
#              readOnly: true
#            - name: gcp-credentials
#              mountPath: "/secret/gcp-credentials"
#              readOnly: true
          containers:
          - name: deploy-worker
            image: gcr.io/kubeflow-ci/deploy-worker:latest
            command:
            - /usr/local/bin/init.sh
            - /src # SRC_DIR
            - kubeflow # REPO_OWNER
            - kubeflow-ci # PROJECT
            - kubeflow-testing # WORKER_CLUSTER
            - /etc/pod-info/labels # JOB_LABELS
            - /mnt/test-data-volume # NFS_MNT
            volumeMounts:
            - name: gcp-credentials
              mountPath: "/secret/gcp-credentials"
              readOnly: true
            - name: pod-info
              mountPath: "/etc/pod-info"
              readOnly: true
            - name: github-token
              mountPath: "/secret/github-token"
              readOnly: true
            - name: test-data-volume
              mountPath: "/mnt/test-data-volume"
              readOnly: false
          restartPolicy: Never
          volumes:
          - name: gcp-credentials
            secret:
              secretName: gcp-credentials
          - name: github-token
            secret:
              secretName: github-token
          - name: test-data-volume
            persistentVolumeClaim:
              claimName: nfs-external
          - name: pod-info
            downwardAPI:
              items:
                - path: "labels"
                  fieldRef:
                    fieldPath: metadata.labels
