apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: debug
  namespace: tektoncd
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  inputs:
    resources:
    - name: workspace
      type: storage
      targetPath: newworkspace
  steps:
  - name: debugger
    image: gcr.io/kubeflow-ci/test-worker:latest
    command:
    - tail
    - -f
    - /dev/null
