apiVersion: batch/v1
kind: Job
metadata:
  name: deployment-snapshot
  clusterName: kubeflow-testing
  namespace: kubeflow-test-infra
spec:
  template:
    spec:
      containers:
      - name: snapshot-worker
        image: gcr.io/kubeflow-ci/snapshot-worker:latest
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/gcp-credentials/key.json
        command:
        - python
        - /usr/local/bin/snapshot_kf_deployment.py
        - kubeflow
        - testing
        - --project=kubeflow-ci
        - --repo_owner=kubeflow
        volumeMounts:
        - name: github-token
          mountPath: "/secret/github-token"
          readOnly: true
        - name: gcp-credentials
          mountPath: "/secret/gcp-credentials"
          readOnly: true
      restartPolicy: "Never"
      volumes:
      - name: github-token
        secret:
          secretName: github-token
      - name: gcp-credentials
        secret:
          secretName: gcp-credentials
